### ISSUE TITLE
color_filter.h and shape_filter.h 

### ISSUE THREAD

**Issue by QNjeason** [JdeRobot/IndustrialRobots#12] opened 2020-12-08 08:04 UTC
These two documents are not available.
#include "pcl_filter/color_filter.h"
#include "pcl_filter/shape_filter.h"
#include <pcl_filter_msgs/ColorFilter.h>
#include <pcl_filter_msgs/ShapeFilter.h>

**Comment by diegomrt** [comment] 2020-12-08 10:15
Have you followed the installation instructions from the [exercise webpage](http://jderobot.github.io/RoboticsAcademy/exercises/IndustrialRobots/machine_vision)? Concretely point 2: 

2. Install PCL and octomap related packages:
```sudo apt-get install ros-melodic-octomap-ros
sudo apt-get install ros-melodic-octomap-msgs
sudo apt-get install ros-melodic-octomap-rviz-plugins
sudo apt install libpcl-dev
sudo apt-get install ros-melodic-perception-pcl
```

**Comment by QNjeason** [comment] 2020-12-08 10:49
I have installed the above tools. The problem is that pcl_filter folder a does not have two header files.
At the same time, there are several problems.
![image](https://user-images.githubusercontent.com/52246049/101474184-bf6da680-3985-11eb-8e0c-5805e4902f6c.png)
![image](https://user-images.githubusercontent.com/52246049/101474261-dd3b0b80-3985-11eb-9ab6-669c0cfdc7f3.png)

**Comment by tohruk** [comment] 2020-12-25 00:54
I faced the same error below.
```
[  4%] Building CXX object IndustrialRobotics/industrial_robots/pcl_filter/CMakeFiles/pcl_filter_server.dir/src/pcl_filter_server.cpp.o
Scanning dependencies of target roboticsgroup_gazebo_mimic_joint_plugin
[  4%] Building CXX object IndustrialRobotics/industrial_robots/robotiq_85_gripper/robotiq_85_simulation/roboticsgroup_gazebo_plugins/CMakeFiles/roboticsgroup_gazebo_mimic_joint_plugin.dir/src/mimic_joint_plugin.cpp.o
/home/user/catkin_ws_mmo500/src/IndustrialRobotics/industrial_robots/pcl_filter/src/pcl_filter_server.cpp:22:10: fatal error: pcl_filter_msgs/ColorFilter.h: No such file or directory
 #include <pcl_filter_msgs/ColorFilter.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I'm not sure this is the right way, but I have resolved the issue by adding the following dependency and `roslaunch mobile_manipulation.launch ` worked.
```
diff --git a/industrial_robots/pcl_filter/CMakeLists.txt b/industrial_robots/pcl_filter/CMakeLists.txt
index 10fc58c..21cd0f1 100644
--- a/industrial_robots/pcl_filter/CMakeLists.txt
+++ b/industrial_robots/pcl_filter/CMakeLists.txt
@@ -53,3 +53,4 @@ target_link_libraries(example ${catkin_LIBRARIES})
 
 add_executable(pcl_filter_server src/pcl_filter_server.cpp)
 target_link_libraries(pcl_filter_server ${catkin_LIBRARIES})
+add_dependencies(pcl_filter_server pcl_filter_msgs_generate_messages_cpp)
```

**Comment by predator4hack** [comment] 2021-04-01 12:04
The problem is with rosdep key of `pcl`, which is actually` libpcl-all-dev`. I've changed the package.xml and now its working perfectly.

**Comment by jmplaza** [comment] 2021-04-04 03:32
Fixed in https://github.com/JdeRobot/IndustrialRobots/pull/13

**Closed by jmplaza** 2021-04-04 03:32 UTC
